FROM openjdk:8-jdk-alpine
MAINTAINER bingcun.chen@wiseloong.com
ADD target/strive-framework-system-manage-server-0.0.2-SNAPSHOT.jar /strive-framework-system-manage-server-0.0.2-SNAPSHOT.jar
EXPOSE 80
ENTRYPOINT ["java","-jar","/strive-framework-system-manage-server-0.0.2-SNAPSHOT.jar"]