version: "2"
services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=phenom
  redis:
    image: redis:6.0.8-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
    - ./redis/data:/data
    - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
  nacos:
    image: nacos/nacos-server:1.3.0
    container_name: nacos
    ports:
      - 8848:8848
    environment:
      - MODE=standalone
    volumes:
    - ./nacos/data:/home/nacos/data
#    - ./nacos/conf:/home/nacos/conf
#    - ./nacos/plugins/mysql:/home/nacos/plugins/mysql
  seata:
    image: seataio/seata-server:1.3.0
    container_name: seata
    ports:
      - 8091:8091
    environment:
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
      - SEATA_IP=172.16.74.170
    volumes:
      - ./seata/conf:/root/seata-config
    depends_on:
      - nacos
      - mysql
  zookeeper:
    image: zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - 2181:2181
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./elk/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elk/elasticsearch/logs:/user/share/elasticsearch/logs
      - ./elk/elasticsearch/plugins/ik:/usr/share/elasticsearch/plugins/ik
  kibana:
    image: kibana:7.9.2
    container_name: kibana
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:7.9.2
    container_name: logstash
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5044:5044
      - 9600:9600
      - 4560:4560
    volumes:
      - ./elk/logstash/config:/usr/share/logstash/config
    command: -f /usr/share/logstash/config/logstash.conf
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq    #数据卷映射
#  integrate-uaap:
#    image: docker.wiseloong.com/snapshot/fighter-microservice-integrate-uaap:1.7.2-SNAPSHOT
#    container_name: integrate-uaap
#    ports:
#      - 9085:8080
#      - 20885:20880
#    expose:
#      - 20880
#    environment:
#      - SPRING.PROFILES.ACTIVE=dev
#      - DUBBO_IP_TO_REGISTRY=192.168.17.20
#      - DUBBO_PORT_TO_REGISTRY=20885
#      - REST_PORT_TO_REGISTRY=9085
#    volumes:
#      - ./microservice-example/integrate-uaap/prop:/root/prop
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#      - seata
#      - zookeeper
