version: "2"
services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=phenom
  redis:
    image: redis:6.0.8-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
    - ./redis/data:/data
    - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
  nacos:
    image: nacos/nacos-server:1.3.0
    container_name: nacos
    ports:
      - 8848:8848
    environment:
      - MODE=standalone
    volumes:
    - ./nacos/data:/home/nacos/data
#    - ./nacos/conf:/home/nacos/conf
#    - ./nacos/plugins/mysql:/home/nacos/plugins/mysql
  seata:
    image: seataio/seata-server:1.3.0
    container_name: seata
    ports:
      - 8091:8091
    environment:
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
      - SEATA_IP=172.16.74.170
    volumes:
      - ./seata/conf:/root/seata-config
    depends_on:
      - nacos
      - mysql
  zookeeper:
    image: zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - 2181:2181
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./elk/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elk/elasticsearch/logs:/user/share/elasticsearch/logs
      - ./elk/elasticsearch/plugins/ik:/usr/share/elasticsearch/plugins/ik
  kibana:
    image: kibana:7.9.2
    container_name: kibana
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:7.9.2
    container_name: logstash
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5044:5044
      - 9600:9600
      - 4560:4560
    volumes:
      - ./elk/logstash/config:/usr/share/logstash/config
    command: -f /usr/share/logstash/config/logstash.conf
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq    #数据卷映射

  namesrv:
    image: rocketmqinc/rocketmq
    container_name: rmqnamesrv
    restart: always
    ports:
      - 9876:9876
    volumes:
      - ./rockmq/logs:/home/rocketmq/logs
      - ./rockmq/store:/home/rocketmq/store
    command: sh mqnamesrv
  broker:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./rockmq/logs:/home/rocketmq/logs
      - ./rockmq/store:/home/rocketmq/store
      - ./rockmq/conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    #command: sh mqbroker -n namesrv:9876
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre
  console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    restart: always
    ports:
      - 8076:8080
    depends_on:
      - namesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rmqnamesrv:9876
      - Dcom.rocketmq.sendMessageWithVIPChannel=false

#  rmqnamesrv:
#    image: foxiswho/rocketmq:server
#    container_name: rmqnamesrv
#    ports:
#      - 9876:9876
#    volumes:
#      - ./data/logs:/opt/logs
#      - ./data/store:/opt/store
#    networks:
#      rmq:
#        aliases:
#          - rmqnamesrv
#  rmqbroker:
#    image: foxiswho/rocketmq:broker
#    container_name: rmqbroker
#    ports:
#      - 10909:10909
#      - 10911:10911
#    volumes:
#      - ./data/logs:/opt/logs
#      - ./data/store:/opt/store
#      - ./data/brokerconf/broker.conf:/etc/rocketmq/broker.conf
#    environment:
#      NAMESRV_ADDR: "rmqnamesrv:9876"
#      JAVA_OPTS: " -Duser.home=/opt"
#      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
#    command: mqbroker -c /etc/rocketmq/broker.conf
#    depends_on:
#      - rmqnamesrv
#    networks:
#      rmq:
#        aliases:
#          - rmqbroker
#  rmqconsole:
#    image: styletang/rocketmq-console-ng
#    container_name: rmqconsole
#    ports:
#      - 8088:8088
#    environment:
#      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
#    depends_on:
#      - rmqnamesrv
#    networks:
#      rmq:
#        aliases:
#          - rmqconsole
#
#networks:
#  rmq:
#    name: rmq
#    driver: bridge
#  integrate-uaap:
#    image: docker.wiseloong.com/snapshot/fighter-microservice-integrate-uaap:1.7.2-SNAPSHOT
#    container_name: integrate-uaap
#    ports:
#      - 9085:8080
#      - 20885:20880
#    expose:
#      - 20880
#    environment:
#      - SPRING.PROFILES.ACTIVE=dev
#      - DUBBO_IP_TO_REGISTRY=192.168.17.20
#      - DUBBO_PORT_TO_REGISTRY=20885
#      - REST_PORT_TO_REGISTRY=9085
#    volumes:
#      - ./microservice-example/integrate-uaap/prop:/root/prop
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#      - seata
#      - zookeeper
